import { CategorySchema } from "./validation"

export const categories: CategorySchema[] = [
  { name: "Pizzas", slug: "pizzas" },
  { name: "Snacks", slug: "snacks" },
  { name: "Coffee", slug: "coffee" },
  { name: "Drinks", slug: "drinks" },
  { name: "Desserts", slug: "desserts" },
  { name: "Sauces", slug: "sauces" },
  { name: "Burgers", slug: "burgers" },
  { name: "Wraps", slug: "wraps" },
  { name: "Pasta", slug: "pasta" },
  { name: "Salads", slug: "salads" }
  // { name: "Soups", slug: "soups" }
  // { name: "Smoothies", slug: "smoothies" },
  // { name: "Juices", slug: "juices" },
  // { name: "Sandwiches", slug: "sandwiches" },
  // { name: "Fries", slug: "fries" },
  // { name: "Tacos", slug: "tacos" },
  // { name: "Burritos", slug: "burritos" },
  // { name: "Wings", slug: "wings" },
  // { name: "Breakfast", slug: "breakfast" },
  // { name: "Hot Dogs", slug: "hot-dogs" },
  // { name: "Grilled", slug: "grilled" },
  // { name: "Steaks", slug: "steaks" },
  // { name: "Seafood", slug: "seafood" },
  // { name: "Sushi", slug: "sushi" },
  // { name: "Appetizers", slug: "appetizers" },
  // { name: "Entrees", slug: "entrees" },
  // { name: "Kids Meals", slug: "kids-meals" },
  // { name: "Specials", slug: "specials" },
  // { name: "Frozen", slug: "frozen" },
  // { name: "Dairy", slug: "dairy" },
  // { name: "Bakery", slug: "bakery" },
  // { name: "Vegan", slug: "vegan" },
  // { name: "Vegetarian", slug: "vegetarian" },
  // { name: "Gluten-Free", slug: "gluten-free" },
  // { name: "Deli", slug: "deli" },
  // { name: "Grains", slug: "grains" },
  // { name: "Ice Cream", slug: "ice-cream" },
  // { name: "Frozen Yogurt", slug: "frozen-yogurt" },
  // { name: "Confectionery", slug: "confectionery" },
  // { name: "Candies", slug: "candies" },
  // { name: "Chocolates", slug: "chocolates" },
  // { name: "Nuts", slug: "nuts" },
  // { name: "Dried Fruits", slug: "dried-fruits" },
  // { name: "Cereals", slug: "cereals" },
  // { name: "Energy Bars", slug: "energy-bars" },
  // { name: "Teas", slug: "teas" },
  // { name: "Herbal Drinks", slug: "herbal-drinks" },
  // { name: "Protein Shakes", slug: "protein-shakes" },
  // { name: "Mocktails", slug: "mocktails" },
  // { name: "Cocktails", slug: "cocktails" },
  // { name: "Spices", slug: "spices" },
  // { name: "Herbs", slug: "herbs" },
  // { name: "Pickles", slug: "pickles" },
  // { name: "Condiments", slug: "condiments" },
  // { name: "Seasonings", slug: "seasonings" },
  // { name: "Toppings", slug: "toppings" },
  // { name: "Side Dishes", slug: "side-dishes" },
  // { name: "Hot Beverages", slug: "hot-beverages" },
  // { name: "Cold Beverages", slug: "cold-beverages" },
  // { name: "Milkshakes", slug: "milkshakes" },
  // { name: "Biscuits", slug: "biscuits" },
  // { name: "Gourmet", slug: "gourmet" },
  // { name: "International", slug: "international" },
  // { name: "Ethnic Foods", slug: "ethnic-foods" },
  // { name: "Prepared Meals", slug: "prepared-meals" },
  // { name: "Organic", slug: "organic" }
]
